### ISSUE TITLE
Runtime Failure unexpected keyword argument 'debug'

### ISSUE THREAD

**Issue by JCobeyTanium** [PaloAltoNetworks-BD/pan-stix#12]
Attempted to run one of the tests and got the following.

python wildfire-to-stix.py -h 2f9dcb186e385b8632d69ab03667263d11814677ea68a601237933d61d5b3c13 -t jpc -o 2f9dcb186e385b8632d69ab03667263d11814677ea68a601237933d61d5b3c13_result.xml
Traceback (most recent call last):
  File "wildfire-to-stix.py", line 148, in <module>
    main()
  File "wildfire-to-stix.py", line 138, in main
    dump_report_to_stix(options)
  File "wildfire-to-stix.py", line 34, in dump_report_to_stix
    sp = panstix.packaging.get_stix_package_from_wfreport(**options)
  File "/Users/jack/Desktop/panXfer/PANGITHUB/pan-stix/panstix/packaging.py", line 49, in get_stix_package_from_wfreport
    ms = wf.get_malware_subject_from_report(**subargs)
  File "/Users/jack/Desktop/panXfer/PANGITHUB/pan-stix/panstix/wf/utils.py", line 162, in get_malware_subject_from_report
    tag=kwargs['tag'])
TypeError: __init__() got an unexpected keyword argument 'debug'

**Comment by jtschichold** [comment]
Added panstix support for pan.xapi logging levels
